### PR TITLE
Release 1.1.2 rc2: changed packages - compile fix

### PR DESCRIPTION
**Pull request by nickl-**
This should do the trick, can't see what I did different.

This is a merge of the release-1.1.2-rc 4ece8af, and feature/packageChange 6e6ee58 branches to allow successful compilation of 1.1.2 release again.

Besides a few minor conflict resolutions I really can't take any credit as it was all alperez. Thank you for doing such a clean and neat package update which allowed me to recompile the release candidate again without much trouble.

Keep up the good work guys! I'll be keeping an eye...

TAKE NOTE: this pull request is against the release-1.1.2-rc branch and not against master.

Just incase =)

### CODE REVIEW

**Comment by alejandroperez** [comment]
Hi Nick. Can you tell me what where the original compilation issue? The branch 1.1.2-rc was meant to be a placeholder for stabilization changes before releasing version 1.1.2 (marked as a tag in github).

1.1.2 depends on bobo 3.0.5 and zoie 3.1.1 (unless I messed up), and those versions don't include the package changes.

If there's a hotfix to 1.1.2, we could create it based on 1.1.2-rc (that's why I left the branch in place) and publish a new artifact under 1.1.2.1 (for example). But for big changes I'd like to integrate with master and use that as the origin for the upcoming 1.2.0 version.

**Comment by nickl-** [comment]
Maybe I should add that the build was done on Mac OSX 10.6 with maven 3.0.3 and native java

```
mvn --version
Apache Maven 3.0.3 (r1075438; 2011-02-28 19:31:09+0200)
Maven home: /usr/share/maven
Java version: 1.6.0_31, vendor: Apple Inc.
Java home: /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
Default locale: en_US, platform encoding: MacRoman
OS name: "mac os x", version: "10.6.8", arch: "x86_64", family: "mac"
```

It would probably also help if I admit that I didn't read the documentation hehehehe and compiled with mvn directly untill I had to solve the kafka issue and discovered that you intended me to use bin/build.sh

I first tried the released [1.1.2 packaged download](https://github.com/linkedin/sensei/tarball/release-1.1.2) which wouldn't compile but I was really adamant to check this out because I heard you guys were up to something but the grapevine got to me late hence why there's probably been quite a bit of water under the bridge since the release and I could understand that some packages might not be where they said they would.

So I forked and tried the branch release-1.1.2-rc and started hacking at it. I will have to start building from scratch again to be able to give you a more detailed report though as I really can't tell you now what exactly the complaints were. I recall the scala snapshot which moved was an issue but fixing that a28a97d was not enough for some reason I thiink I got as far as a package that was somewhere com.linkedin or something and I knew it would not help to look for it elsewhere. I studied the commit graph and found that there was a package change branch feature/packageChange. Investigating this closer I was satisfied that it purely contained actual package updates and nothing else and that the few hops before the branch and the release were also cosmetic so I crossed my fingers, closed my eyes and hit merge.

Only two pom.xml files were in conflict and I think it was due to the commented out scala dependency on master that git did not like. Fixing these by hand I closed my eyes again and hit compile which got to the tests not finding zookeeper at which point I ran the bin/build.sh to bypass tests and tah-dah I hit all the green flags started up and oh the joy very nice. 

The console doesn't work and examples won't compile either, if I recall, luckily cars has a jsp so that worked perfectly besides the lack of compilation. I went through great lengths to ensure that the commit does not spaghetti the commit branch so you will be able to see exactly where I got off and back on again because the pull request has also been done on a separate branch re. release-1.1.2-rc2 

I wish I could give you more info let me know if any of these make any sense and what you would like me to pin point for you. If you ask me all these changes are already on master I did not add anything myself so no need to merge with master again it was purely to make release-1.1.2 able to build again 2 months after it's release, or that was my aim at least.

Keep up the good work and feel free to push on my button if I could help in any way.

**Comment by nickl-** [comment]
My rc2 is = to your 1.1.2.1 so we had the same idea with different words.

No major changes only package updates, I will try and get you more info but look at the commit graph it should explain everything you need to know.

**Comment by nickl-** [comment]
I notice that the documentation changes crept into this pull request automagically without the functionality to counter the inconvenience I made a new pull request #45 which only includes the changes under review here.

Herewith a detailed account of compile errors as per your request:
- Running ./bin/build.sh on the release-1.1.2-rc branch gets aborted with the following maven error

```
[ERROR] Failed to execute goal on project sensei-core: Could not resolve dependencies for project com.senseidb:sensei-core:jar:1.1.2: Failed to collect dependencies for [org.jolokia:jolokia-core:jar:0.90 (compile), com.google.protobuf:protobuf-java:jar:2.4.0a (compile), commons-codec:commons-codec:jar:1.4 (compile), org.apache.hadoop:hadoop-core:jar:0.20.2 (compile), com.linkedin.zoie:zoie-core:jar:3.1.1 (compile), com.linkedin.zoie:zoie-jms:jar:3.1.1 (compile), it.unimi.dsi:fastutil:jar:6.4.3 (compile), org.springframework:spring:jar:2.5.5 (compile), org.slf4j:slf4j-api:jar:1.6.1 (compile), org.slf4j:slf4j-log4j12:jar:1.6.1 (compile), commons-lang:commons-lang:jar:2.5 (compile), commons-io:commons-io:jar:2.1 (compile), org.apache.httpcomponents:httpclient:jar:4.1.3 (compile), com.browseengine.bobo:bobo-browse:jar:3.0.5 (compile), commons-configuration:commons-configuration:jar:1.6 (compile), org.json:json:jar:20080701 (compile), com.linkedin:norbert_2.8.1:jar:0.6.12 (compile), com.yammer.metrics:metrics-core:jar:2.0.0-RC0 (compile), javax.servlet:servlet-api:jar:2.5 (compile), org.mortbay.jetty:jetty:jar:6.1.26 (compile), org.apache.zookeeper:zookeeper:jar:3.3.3 (compile), org.antlr:antlr:jar:3.4 (compile), org.javassist:javassist:jar:3.16.1-GA (compile), junit:junit:jar:4.5 (test)]: Failed to read artifact descriptor for com.linkedin.zoie:zoie-core:jar:3.1.1: Could not transfer artifact com.linkedin.zoie:zoie-core:pom:3.1.1 from/to Scala Tools Repository (http://nexus.scala-tools.org/content/repositories/snapshots/): Error transferring file: Server returned HTTP response code: 502 for URL: http://nexus.scala-tools.org/content/repositories/snapshots/com/linkedin/zoie/zoie-core/3.1.1/zoie-core-3.1.1.pom -> [Help 1]

```

Updating sensei-parent/pom.xml to comment out the faulty repository reference, in the same fashion as current master branch, allows build to continue.

``` diff
git diff sensei-parent/pom.xml 
diff --git a/sensei-parent/pom.xml b/sensei-parent/pom.xml
index 1211df0..a7d3d87 100644
--- a/sensei-parent/pom.xml
+++ b/sensei-parent/pom.xml
@@ -130,10 +130,10 @@
                <enabled>false</enabled>
               </snapshots>
            </repository>
-           <repository>
+           <!--<repository>
              <id>Scala Tools Repository</id>
              <url>http://nexus.scala-tools.org/content/repositories/snapshots/</url>
-           </repository>
+           </repository>-->
       <repository>
         <id>labs-consol-release</id>
         <name>ConSol* Labs Repository (Releases)</name>
```
- The 2nd build error complaining that it cannot find zoie-core ver 3.1.1

```
[ERROR] Failed to execute goal on project sensei-core: Could not resolve dependencies for project com.senseidb:sensei-core:jar:1.1.2: The following artifacts could not be resolved: com.linkedin.zoie:zoie-core:jar:3.1.1, com.linkedin.zoie:zoie-jms:jar:3.1.1, com.browseengine.bobo:bobo-browse:jar:3.0.5: Could not find artifact com.linkedin.zoie:zoie-core:jar:3.1.1 in repository.jboss.org (http://repository.jboss.org/nexus/content/groups/public/) -> [Help 1]
```
- The 3rd build error complaining that it cannot find bobo 3.0.5

``` diff
[ERROR] Failed to execute goal on project sensei-core: Could not resolve dependencies for project com.senseidb:sensei-core:jar:1.1.2: Failure to find com.browseengine.bobo:bobo-browse:jar:3.0.5 in http://repository.jboss.org/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of repository.jboss.org has elapsed or updates are forced -> [Help 1]
```

These can be manually rectified instead of merging with feature/packageChange by updating the version numbers in sensei-core/pom.xml as per the following diff;   

``` diff
diff --git a/sensei-core/pom.xml b/sensei-core/pom.xml
index 1756493..592b9c2 100644
--- a/sensei-core/pom.xml
+++ b/sensei-core/pom.xml
@@ -192,14 +192,8 @@

                <dependency>
                        <groupId>com.linkedin.zoie</groupId>
-                       <artifactId>zoie-core</artifactId>
-                       <version>3.1.1</version>
-               </dependency>
-               
-               <dependency>
-                       <groupId>com.linkedin.zoie</groupId>
                        <artifactId>zoie-jms</artifactId>
-                       <version>3.1.1</version>
+                       <version>3.2.0-SNAPSHOT</version>
                </dependency>

                <dependency>
@@ -249,7 +243,7 @@
                <dependency>
                        <groupId>com.browseengine.bobo</groupId>
                        <artifactId>bobo-browse</artifactId>
-                       <version>3.0.5</version>
+                       <version>3.1.0-SNAPSHOT</version>
                        <!-- type>jar</type -->
                </dependency>
```

Since the new distributions include package changes all references need to be change for proj.zoie -> com.linkedin.zoie and com.browseengine.bobo -> com.linkedin.bobo,

Using the following commands: 

```
find . \( ! -regex '.*/\..*' \) -type f -exec sed -i 0 's/proj.zoie/com.linkedin.zoie/' {} \;
find . \( ! -regex '.*/\..*' \) -type f -exec sed -i 0 's/com.browseengine.bobo/com.linkedin.bobo/' {} \;
```

Which unfortunately messed up some files by removing the last blank line and some binaries especially image files but these were easily rectified, because it was obvious that these changes did not have the desired effect, by interactively rolling them back with:
git checkout -p 
- Finally trying to compile again maven was still unable to find the packages with the following error:

```
[ERROR] Failed to execute goal on project sensei-core: Could not resolve dependencies for project com.senseidb:sensei-core:jar:1.1.2: The following artifacts could not be resolved: com.linkedin.zoie:zoie-jms:jar:3.2.0-SNAPSHOT, com.linkedin.bobo:bobo-browse:jar:3.1.0-SNAPSHOT: Failure to find com.linkedin.zoie:zoie-jms:jar:3.2.0-SNAPSHOT in http://labs.consol.de/maven/repository was cached in the local repository, resolution will not be reattempted until the update interval of labs-consol-release has elapsed or updates are forced -> [Help 1]
```

Comparing the manual changes to the changes produced from merging with feature/packageChange revealed the only differences still remaining are that the repository org.sonatype.oss is commented out in sensei-parent/pom.xml and re-enabling this concluding a perfect 1/1 replication of the changes suggested it naturally has o build now.

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] sensei parent ..................................... SUCCESS [27.332s]
[INFO] sensei core ....................................... SUCCESS [6:13.885s]
[INFO] sensei gateways ................................... SUCCESS [2:40.427s]
[INFO] sensei hadoop indexing ............................ SUCCESS [1:09.891s]
[INFO] sensei java client ................................ SUCCESS [19.440s]
[INFO] sensei war ........................................ SUCCESS [13.854s]
[INFO] sensei ............................................ SUCCESS [1:16.800s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12:22.085s
[INFO] Finished at: Sat May 19 16:18:15 SAST 2012
[INFO] Final Memory: 32M/81M
[INFO] ------------------------------------------------------------------------
```

**Comment by nickl-** [comment]
After further investigation regarding your intent to have this release 1.1.2 be dependent on bobo 3.0.5 and zoie 3.1.1 you failed to provide information on where they should be found.

They have not been added to the maven repository @ http://org.sonatype.oss as are previous versions and the new ones.

These are custom linkedin packoged versions as the official releases are also not anywhere near these version numbers.

There are several repositories referred to in one way or another which also don't include these specific releases, amongst them: 
https://github.com/senseidb
https://github.com/javasoze

I eventually located what seems to be the desired revisions at:
https://github.com/linkedin/zoie/zipball/release-3.1.1
and
https://github.com/linkedin/bobo/zipball/release-3.0.5

I was unable to deduce how you intended these to be included in the sensei project so I eventually resorted to extracting them into the sensei folder and including them as modules to be build before core in the root pom.xml. Which I am happy to report did allow fo a successful build. =)

If you can explain how you would like to have these dependencies resolved or maybe facilitate adding the packages to the maven repository where they can then be located on build I will gladly update the pull request so that we can finally build and test release 1.1.2.

**Comment by nickl-** [comment]
Some questions which I find baffling:
1. Why has no one else had these problems since the release in March?
2. Where are we suppose to look for documentation regarding the releases?
3. Can we please have this process explained and referenced on the project page.
4. There are still other items outstanding in this release, automated testing, building the examples and clients, etc. Would it not be advisable to take the time to have these fixed in still another release 1.1.2.2 as per your suggestion so that we can complete this as a working release in all it's aspects and start getting usable feedback from actually testing this?

Only suggestions but I am sure we are loosing valuable feedback from others not willing to suffer this amount of frustration, would you agree?

**Comment by alejandroperez** [comment]
Nickl, we had some problems with the process of uploading the binary artifacts to maven central. I think they are all solved in the latest releases. My apologies.

**Pull request closed without merging**
